version: '3.7'
services:
  nodeserver:
    build:
      context: ./app
    ports:
      - "3333:3333"
  redis:
    image: "redis:alpine"
    volumes:
      - .docker/data/redis:/data
  db:
    image: mongo
    volumes:
      - .docker/data/db:/data/db
    restart: unless-stopped
