version: '3.7'
services:
  web:
    image: untadee/survey-api:latest
    build: .
    networks:
      - webnet
      - traefik-public
    depends_on:
      - redis
    # environment:
      # - REDIS_HOST=redis
      # - MONGODB_URL=mongodb://admin:123123@mongodb:27017/project-1-web?authSource=admin
    # service deployment
    deploy:
      # service resource management
      resources:
        # Hard limit - Docker does not allow to allocate more
        limits:
          cpus: '0.50'
          memory: 512M
        # Soft limit - Docker makes best effort to return to it
        reservations:
          cpus: '0.50'
          memory: 256M
      # service restart policy
      replicas: 10
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.survey-web.rule=Host(`rais.dista.uninsubria.it`)
        - traefik.http.routers.survey-web.entrypoints=https
        - traefik.http.routers.survey-web.tls=true
        # - traefik.http.middlewares.survey-strip-prefix.stripprefix.prefixes=/survey
        # - traefik.http.routers.survey-web.middlewares=survey-strip-prefix
        - traefik.http.services.survey-web.loadbalancer.server.port=3333

  # redis:
  #   image: "redis:alpine"
  #   networks:
  #     - webnet
  #   ports:
  #     - "6380:6379"
  #   volumes:
  #     - /home/$USER/redis-data:/var/lib/redis

  # mongodb:
  #   image: mongo
  #   restart: always
  #   networks:
  #     - webnet
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=123123
  #   volumes:
  #     - /home/son.ha/mongodb/database:/data/db
  #   ports:
  #     - 193.206.183.134:27018:27017
networks:
  webnet:
  traefik-public:
    external: true
volumes:
  data:


